### ISSUE TITLE
Error not finding utils

### ISSUE THREAD

**Issue by brando90** [pcattori/namespaces#15]
Seems utils is being imported but not used in the current 3.0.0. For now Im using 1.0.0 that doesn't have that bug.

**Comment by brando90** [comment]
```
(venv2) brandomiranda~/Documents/MIT/MEng/hbf_tensorflow_code/tf_experiments_scripts $ python batch_main.py
Traceback (most recent call last):
  File "batch_main.py", line 12, in <module>
    import namespaces as ns
  File "/Users/brandomiranda/Documents/MIT/MEng/hbf_tensorflow_code/venv2/lib/python3.5/site-packages/namespaces/__init__.py", line 1, in <module>
    from namespaces.utils import *
ImportError: No module named 'namespaces.utils'
```

**Comment by brando90** [comment]
Maybe its related to the version but 1.0.0 can't find frozenNS:

>>> fns = ns.FrozenNamespace(ns)
Traceback (most recent call last):
  File "/Users/brandomiranda/Documents/MIT/MEng/hbf_tensorflow_code/venv2/lib/python3.5/site-packages/namespaces/namespace.py", line 40, in __getattr__
    return dict.__getitem__(self, name)
KeyError: 'FrozenNamespace'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/brandomiranda/Documents/MIT/MEng/hbf_tensorflow_code/venv2/lib/python3.5/site-packages/namespaces/namespace.py", line 43, in __getattr__
    "'{}' object has no attribute '{}'".format(type(self).__name__, name)
AttributeError: 'Namespace' object has no attribute 'FrozenNamespace'
>>> fns = ns.FrozenNamespace(ns)
Traceback (most recent call last):
  File "/Users/brandomiranda/Documents/MIT/MEng/hbf_tensorflow_code/venv2/lib/python3.5/site-packages/namespaces/namespace.py", line 40, in __getattr__
    return dict.__getitem__(self, name)
KeyError: 'FrozenNamespace'

During handling of the above exception, another exception occurred:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/brandomiranda/Documents/MIT/MEng/hbf_tensorflow_code/venv2/lib/python3.5/site-packages/namespaces/namespace.py", line 43, in __getattr__
    "'{}' object has no attribute '{}'".format(type(self).__name__, name)
AttributeError: 'Namespace' object has no attribute 'FrozenNamespace'
```

**Comment by pcattori** [comment]
#16 fixed version 3.0.0

**Comment by pcattori** [comment]
@brando90 the "bug" in 1.0.0 is not actually a bug. you are overloading `ns` to be both the name of the module and the name of a specific instance of `Namespace`, so in the line of code `fns = ns.FrozenNamespace(ns)`, `ns` is a `Namespace` instance, not the `namespaces` module

**Comment by brando90** [comment]
oh yea oops.
